<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phoneNumber</name>
   <tag></tag>
   <elementGuidId>39629ac9-e87c-47d1-b2ec-bf62f9809799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.btn-log.border-grey.int_tel_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f44b8444-6265-48b6-bcda-4097cd7e19df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>12c772bc-20f1-4467-9b57-b2a45bf9dbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-log border-grey int_tel_input</value>
      <webElementGuid>b0ea6986-0c30-4dd2-8b65-686781b031d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>27462d10-c530-412a-8468-51048b06cfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>8123 4567</value>
      <webElementGuid>ef88d31d-7fa3-4f9a-96b5-5f1273b03d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>intl-0</value>
      <webElementGuid>e3f8c894-77fe-41bc-aab5-fdd71ebd2c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8692be3c-e465-482b-b12d-e942a56806d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 register-row&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/input[@class=&quot;form-control btn-log border-grey int_tel_input&quot;]</value>
      <webElementGuid>c44d6268-ebe5-4746-a947-2565639c3ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>31249d96-0683-4641-8db4-5032bcbf987d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[5]/div[2]/div/input</value>
      <webElementGuid>ef9f2799-b6ce-446a-a47c-077c7f14b962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>a8a2a05a-26ab-4315-8b07-bf9e067b77ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '8123 4567']</value>
      <webElementGuid>bbbe0517-3b96-471e-8857-c247f96ea7b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
